# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

resources:
  containers:
    - container: cassandra
      image: cassandra:3

pool:
  vmImage: 'ubuntu-latest'

services:
  cassandra: cassandra

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get install -y netcat
      while ! nc -z localhost 9042 </dev/null; do sleep 10; done
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
